id: P000188
initial_creation_type: ebook
source_metadata:
  title: ༈ ཕན་ཡོན་ཕྱོགས་སྒྲིག་འདོད་འཇོའི་བུམ་བཟང་བཞུགས་སོ།
  authors:
  - མཛད་པ་པོ། མཁས་གྲུབ་ཀརྨ་ཆགས་མེད། གཏེར་ཆེན་ཀརྨ་གླིང་པ།
  - ཨོ་རྒྱན་པདྨ་འབྱུང་གནས། རྒྱལ་དབང་མཁའ་ཁྱབ་རྡོ་རྗེ།
  layers:
  - book_title
  - author
  - chapter_title
  - tsawa
  - quotation
  - sabche
  - yigchung
  id: BEN-LB-005
web_metadata:
  title:
    en: A Wish-Granting Vase:Collected Works on the Benefits of Offering Butter Lamps
      and Incense, Saving Life, Doing Prostrations, and So On
    bo: ཕན་ཡོན་ཕྱོགས་སྒྲིག་འདོད་འཇོའི་བུམ་བཟང་བཞུགས་སོ།། །།
  collection:
    en: Benchen Library–  Book 5
    bo: བེན་ཆེན་དཔེ་མཛོད་ཁང་།–  དེབ། ༥
  author:
    en: Authors:Fifteenth Karmapa Khakhyab Dorje,Khedrub Karma Chagme,Padmasambhava,Terchen
      Karma Lingpa
    bo: ཀརྨ་པ་སྐུ་ཕྲེང་བཅོ་ལྔ་པ་མཁའ་ཁྱབ་རྡོ་རྗེ།,གཏེར་ཆེན་ཀརྨ་གླིང་པ།,པདྨ་སཾ་བྷ་བ།,མཁས་གྲུབ་ཀརྨ་ཆགས་མེད།
  pusblisher:
    en: Benchen Publications
    bo: བེན་ཆེན་སློབ་གཉེར་ཁང་།
  sku: BEN-LB-005
  category:
    en: Mind Training
    bo: བློ་སྦྱོང།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: BEN-LB-005.epub
  description:
    en: ''
    bo: པོད་འདིའི་ནང་ལ་མཁས་གྲུབ་ཀརྨ་ཆགས་མེད། གཏེར་ཆེན་ཀརྨ་གླིང་པ། ཨོ་རྒྱན་པདྨ་འབྱུང་གནས།
      རྒྱལ་དབང་མཁའ་ཁྱབ་རྡོ་རྗེ་ལ་སོགས་ཀྱིས་མཛད་པའི་སྲོག་བླུ་དང་ཕྱག་འཚལ་ལ་སོགས་ཀྱི་དགེ་སྦྱོར་གྱི་ཕན་ཡོན་རབ་རིམ་ཕྱོགས་བསྒྲིགས་ཞུས་ཡོད།
